// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: nexus/backend/v1/models.proto

package backendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AloInfo_Status int32

const (
	AloInfo_STATUS_UNSPECIFIED AloInfo_Status = 0
	AloInfo_RUNNING            AloInfo_Status = 1
	AloInfo_COMPLETED          AloInfo_Status = 2
)

// Enum value maps for AloInfo_Status.
var (
	AloInfo_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "RUNNING",
		2: "COMPLETED",
	}
	AloInfo_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"RUNNING":            1,
		"COMPLETED":          2,
	}
)

func (x AloInfo_Status) Enum() *AloInfo_Status {
	p := new(AloInfo_Status)
	*p = x
	return p
}

func (x AloInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AloInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_backend_v1_models_proto_enumTypes[0].Descriptor()
}

func (AloInfo_Status) Type() protoreflect.EnumType {
	return &file_nexus_backend_v1_models_proto_enumTypes[0]
}

func (x AloInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AloInfo_Status.Descriptor instead.
func (AloInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_nexus_backend_v1_models_proto_rawDescGZIP(), []int{1, 0}
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Http        bool   `protobuf:"varint,3,opt,name=http,proto3" json:"http,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetHttp() bool {
	if x != nil {
		return x.Http
	}
	return false
}

// An ALO is started via a
type AloInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         AloInfo_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=nexus.backend.v1.AloInfo_Status" json:"status,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HttpResultUrls []string          `protobuf:"bytes,4,rep,name=http_result_urls,json=httpResultUrls,proto3" json:"http_result_urls,omitempty"`
}

func (x *AloInfo) Reset() {
	*x = AloInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AloInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AloInfo) ProtoMessage() {}

func (x *AloInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AloInfo.ProtoReflect.Descriptor instead.
func (*AloInfo) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *AloInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AloInfo) GetStatus() AloInfo_Status {
	if x != nil {
		return x.Status
	}
	return AloInfo_STATUS_UNSPECIFIED
}

func (x *AloInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AloInfo) GetHttpResultUrls() []string {
	if x != nil {
		return x.HttpResultUrls
	}
	return nil
}

var File_nexus_backend_v1_models_proto protoreflect.FileDescriptor

var file_nexus_backend_v1_models_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x22, 0x53, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x22, 0xbd, 0x02, 0x0a, 0x07, 0x41, 0x6c, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x43, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x6c, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x28, 0x0a, 0x10, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x74, 0x74,
	0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nexus_backend_v1_models_proto_rawDescOnce sync.Once
	file_nexus_backend_v1_models_proto_rawDescData = file_nexus_backend_v1_models_proto_rawDesc
)

func file_nexus_backend_v1_models_proto_rawDescGZIP() []byte {
	file_nexus_backend_v1_models_proto_rawDescOnce.Do(func() {
		file_nexus_backend_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_nexus_backend_v1_models_proto_rawDescData)
	})
	return file_nexus_backend_v1_models_proto_rawDescData
}

var file_nexus_backend_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nexus_backend_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nexus_backend_v1_models_proto_goTypes = []interface{}{
	(AloInfo_Status)(0), // 0: nexus.backend.v1.AloInfo.Status
	(*Service)(nil),     // 1: nexus.backend.v1.Service
	(*AloInfo)(nil),     // 2: nexus.backend.v1.AloInfo
	nil,                 // 3: nexus.backend.v1.AloInfo.MetadataEntry
}
var file_nexus_backend_v1_models_proto_depIdxs = []int32{
	0, // 0: nexus.backend.v1.AloInfo.status:type_name -> nexus.backend.v1.AloInfo.Status
	3, // 1: nexus.backend.v1.AloInfo.metadata:type_name -> nexus.backend.v1.AloInfo.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nexus_backend_v1_models_proto_init() }
func file_nexus_backend_v1_models_proto_init() {
	if File_nexus_backend_v1_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nexus_backend_v1_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AloInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nexus_backend_v1_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nexus_backend_v1_models_proto_goTypes,
		DependencyIndexes: file_nexus_backend_v1_models_proto_depIdxs,
		EnumInfos:         file_nexus_backend_v1_models_proto_enumTypes,
		MessageInfos:      file_nexus_backend_v1_models_proto_msgTypes,
	}.Build()
	File_nexus_backend_v1_models_proto = out.File
	file_nexus_backend_v1_models_proto_rawDesc = nil
	file_nexus_backend_v1_models_proto_goTypes = nil
	file_nexus_backend_v1_models_proto_depIdxs = nil
}
