// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: nexus/backend/v1/service.proto

package backendpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set of services to create or update.
	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	// If set, the set of services to remove. Cannot have values if replace is
	// true.
	RemoveServices []string `protobuf:"bytes,2,rep,name=remove_services,json=removeServices,proto3" json:"remove_services,omitempty"`
	// If true, will replace all existing services with given services. Cannot be
	// true if remove_services has values.
	Replace bool `protobuf:"varint,3,opt,name=replace,proto3" json:"replace,omitempty"`
}

func (x *UpdateServicesRequest) Reset() {
	*x = UpdateServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServicesRequest) ProtoMessage() {}

func (x *UpdateServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServicesRequest.ProtoReflect.Descriptor instead.
func (*UpdateServicesRequest) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateServicesRequest) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *UpdateServicesRequest) GetRemoveServices() []string {
	if x != nil {
		return x.RemoveServices
	}
	return nil
}

func (x *UpdateServicesRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

type UpdateServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set of created/updated services.
	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *UpdateServicesResponse) Reset() {
	*x = UpdateServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServicesResponse) ProtoMessage() {}

func (x *UpdateServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServicesResponse.ProtoReflect.Descriptor instead.
func (*UpdateServicesResponse) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{2}
}

type GetServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type MetadataValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *MetadataValues) Reset() {
	*x = MetadataValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValues) ProtoMessage() {}

func (x *MetadataValues) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValues.ProtoReflect.Descriptor instead.
func (*MetadataValues) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Service   string                     `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Metadata  map[string]*MetadataValues `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body      []byte                     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // TODO(cretz): Remote information, e.g. caller addr and TLS?
	// Types that are assignable to Protocol:
	//	*CallRequest_Http_
	Protocol isCallRequest_Protocol `protobuf_oneof:"protocol"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *CallRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallRequest) GetMetadata() map[string]*MetadataValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CallRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (m *CallRequest) GetProtocol() isCallRequest_Protocol {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (x *CallRequest) GetHttp() *CallRequest_Http {
	if x, ok := x.GetProtocol().(*CallRequest_Http_); ok {
		return x.Http
	}
	return nil
}

type isCallRequest_Protocol interface {
	isCallRequest_Protocol()
}

type CallRequest_Http_ struct {
	Http *CallRequest_Http `protobuf:"bytes,5,opt,name=http,proto3,oneof"`
}

func (*CallRequest_Http_) isCallRequest_Protocol() {}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata  map[string]*MetadataValues `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// TODO(cretz): What about streaming large HTTP responses?
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Types that are assignable to Protocol:
	//	*CallResponse_Http_
	Protocol isCallResponse_Protocol `protobuf_oneof:"protocol"`
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CallResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallResponse) GetMetadata() map[string]*MetadataValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CallResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (m *CallResponse) GetProtocol() isCallResponse_Protocol {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (x *CallResponse) GetHttp() *CallResponse_Http {
	if x, ok := x.GetProtocol().(*CallResponse_Http_); ok {
		return x.Http
	}
	return nil
}

type isCallResponse_Protocol interface {
	isCallResponse_Protocol()
}

type CallResponse_Http_ struct {
	Http *CallResponse_Http `protobuf:"bytes,4,opt,name=http,proto3,oneof"`
}

func (*CallResponse_Http_) isCallResponse_Protocol() {}

type StreamTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Task:
	//	*StreamTasksRequest_Init_
	//	*StreamTasksRequest_CallResponse
	Task isStreamTasksRequest_Task `protobuf_oneof:"task"`
}

func (x *StreamTasksRequest) Reset() {
	*x = StreamTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTasksRequest) ProtoMessage() {}

func (x *StreamTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTasksRequest.ProtoReflect.Descriptor instead.
func (*StreamTasksRequest) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{7}
}

func (m *StreamTasksRequest) GetTask() isStreamTasksRequest_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *StreamTasksRequest) GetInit() *StreamTasksRequest_Init {
	if x, ok := x.GetTask().(*StreamTasksRequest_Init_); ok {
		return x.Init
	}
	return nil
}

func (x *StreamTasksRequest) GetCallResponse() *CallResponse {
	if x, ok := x.GetTask().(*StreamTasksRequest_CallResponse); ok {
		return x.CallResponse
	}
	return nil
}

type isStreamTasksRequest_Task interface {
	isStreamTasksRequest_Task()
}

type StreamTasksRequest_Init_ struct {
	Init *StreamTasksRequest_Init `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type StreamTasksRequest_CallResponse struct {
	CallResponse *CallResponse `protobuf:"bytes,2,opt,name=call_response,json=callResponse,proto3,oneof"`
}

func (*StreamTasksRequest_Init_) isStreamTasksRequest_Task() {}

func (*StreamTasksRequest_CallResponse) isStreamTasksRequest_Task() {}

type StreamTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Task:
	//	*StreamTasksResponse_CallRequest
	Task isStreamTasksResponse_Task `protobuf_oneof:"task"`
}

func (x *StreamTasksResponse) Reset() {
	*x = StreamTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTasksResponse) ProtoMessage() {}

func (x *StreamTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTasksResponse.ProtoReflect.Descriptor instead.
func (*StreamTasksResponse) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{8}
}

func (m *StreamTasksResponse) GetTask() isStreamTasksResponse_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *StreamTasksResponse) GetCallRequest() *CallRequest {
	if x, ok := x.GetTask().(*StreamTasksResponse_CallRequest); ok {
		return x.CallRequest
	}
	return nil
}

type isStreamTasksResponse_Task interface {
	isStreamTasksResponse_Task()
}

type StreamTasksResponse_CallRequest struct {
	CallRequest *CallRequest `protobuf:"bytes,2,opt,name=call_request,json=callRequest,proto3,oneof"`
}

func (*StreamTasksResponse_CallRequest) isStreamTasksResponse_Task() {}

type CallRequest_Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CallRequest_Http) Reset() {
	*x = CallRequest_Http{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest_Http) ProtoMessage() {}

func (x *CallRequest_Http) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest_Http.ProtoReflect.Descriptor instead.
func (*CallRequest_Http) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{5, 1}
}

func (x *CallRequest_Http) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest_Http) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CallResponse_Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *CallResponse_Http) Reset() {
	*x = CallResponse_Http{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse_Http) ProtoMessage() {}

func (x *CallResponse_Http) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse_Http.ProtoReflect.Descriptor instead.
func (*CallResponse_Http) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CallResponse_Http) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type CallResponse_Grpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If this is not 0 (i.e. OK), the body is ignored
	StatusCode    int32      `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage string     `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	StatusDetails *anypb.Any `protobuf:"bytes,3,opt,name=status_details,json=statusDetails,proto3" json:"status_details,omitempty"`
}

func (x *CallResponse_Grpc) Reset() {
	*x = CallResponse_Grpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse_Grpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse_Grpc) ProtoMessage() {}

func (x *CallResponse_Grpc) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse_Grpc.ProtoReflect.Descriptor instead.
func (*CallResponse_Grpc) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{6, 2}
}

func (x *CallResponse_Grpc) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CallResponse_Grpc) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *CallResponse_Grpc) GetStatusDetails() *anypb.Any {
	if x != nil {
		return x.StatusDetails
	}
	return nil
}

type StreamTasksRequest_Init struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *StreamTasksRequest_Init) Reset() {
	*x = StreamTasksRequest_Init{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nexus_backend_v1_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTasksRequest_Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTasksRequest_Init) ProtoMessage() {}

func (x *StreamTasksRequest_Init) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_v1_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTasksRequest_Init.ProtoReflect.Descriptor instead.
func (*StreamTasksRequest_Init) Descriptor() ([]byte, []int) {
	return file_nexus_backend_v1_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *StreamTasksRequest_Init) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_nexus_backend_v1_service_proto protoreflect.FileDescriptor

var file_nexus_backend_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x76, 0x31, 0x1a, 0x1d, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x22, 0x4f,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x78,
	0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xfa, 0x02,
	0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x48, 0x74, 0x74, 0x70, 0x48, 0x00, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x1a, 0x5d, 0x0a,
	0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x30, 0x0a, 0x04,
	0x48, 0x74, 0x74, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x0a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xe8, 0x03, 0x0a, 0x0c, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x48, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6e,
	0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x48, 0x00, 0x52, 0x04, 0x68,
	0x74, 0x74, 0x70, 0x1a, 0x5d, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x27, 0x0a, 0x04, 0x48, 0x74, 0x74, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x8b, 0x01, 0x0a, 0x04,
	0x47, 0x72, 0x70, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xc8, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x04,
	0x69, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x65, 0x78,
	0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x45, 0x0a,
	0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x22, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x22, 0x61, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b,
	0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74,
	0x61, 0x73, 0x6b, 0x32, 0xd7, 0x03, 0x0a, 0x0e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x84, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x27, 0x2e, 0x6e, 0x65, 0x78, 0x75,
	0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x78, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x6e,
	0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x62, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12,
	0x1d, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x3a, 0x01, 0x2a, 0x12, 0x60, 0x0a, 0x0b, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x24, 0x2e, 0x6e, 0x65, 0x78,
	0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nexus_backend_v1_service_proto_rawDescOnce sync.Once
	file_nexus_backend_v1_service_proto_rawDescData = file_nexus_backend_v1_service_proto_rawDesc
)

func file_nexus_backend_v1_service_proto_rawDescGZIP() []byte {
	file_nexus_backend_v1_service_proto_rawDescOnce.Do(func() {
		file_nexus_backend_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_nexus_backend_v1_service_proto_rawDescData)
	})
	return file_nexus_backend_v1_service_proto_rawDescData
}

var file_nexus_backend_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nexus_backend_v1_service_proto_goTypes = []interface{}{
	(*UpdateServicesRequest)(nil),   // 0: nexus.backend.v1.UpdateServicesRequest
	(*UpdateServicesResponse)(nil),  // 1: nexus.backend.v1.UpdateServicesResponse
	(*GetServicesRequest)(nil),      // 2: nexus.backend.v1.GetServicesRequest
	(*GetServicesResponse)(nil),     // 3: nexus.backend.v1.GetServicesResponse
	(*MetadataValues)(nil),          // 4: nexus.backend.v1.MetadataValues
	(*CallRequest)(nil),             // 5: nexus.backend.v1.CallRequest
	(*CallResponse)(nil),            // 6: nexus.backend.v1.CallResponse
	(*StreamTasksRequest)(nil),      // 7: nexus.backend.v1.StreamTasksRequest
	(*StreamTasksResponse)(nil),     // 8: nexus.backend.v1.StreamTasksResponse
	nil,                             // 9: nexus.backend.v1.CallRequest.MetadataEntry
	(*CallRequest_Http)(nil),        // 10: nexus.backend.v1.CallRequest.Http
	nil,                             // 11: nexus.backend.v1.CallResponse.MetadataEntry
	(*CallResponse_Http)(nil),       // 12: nexus.backend.v1.CallResponse.Http
	(*CallResponse_Grpc)(nil),       // 13: nexus.backend.v1.CallResponse.Grpc
	(*StreamTasksRequest_Init)(nil), // 14: nexus.backend.v1.StreamTasksRequest.Init
	(*Service)(nil),                 // 15: nexus.backend.v1.Service
	(*anypb.Any)(nil),               // 16: google.protobuf.Any
}
var file_nexus_backend_v1_service_proto_depIdxs = []int32{
	15, // 0: nexus.backend.v1.UpdateServicesRequest.services:type_name -> nexus.backend.v1.Service
	15, // 1: nexus.backend.v1.UpdateServicesResponse.services:type_name -> nexus.backend.v1.Service
	15, // 2: nexus.backend.v1.GetServicesResponse.services:type_name -> nexus.backend.v1.Service
	9,  // 3: nexus.backend.v1.CallRequest.metadata:type_name -> nexus.backend.v1.CallRequest.MetadataEntry
	10, // 4: nexus.backend.v1.CallRequest.http:type_name -> nexus.backend.v1.CallRequest.Http
	11, // 5: nexus.backend.v1.CallResponse.metadata:type_name -> nexus.backend.v1.CallResponse.MetadataEntry
	12, // 6: nexus.backend.v1.CallResponse.http:type_name -> nexus.backend.v1.CallResponse.Http
	14, // 7: nexus.backend.v1.StreamTasksRequest.init:type_name -> nexus.backend.v1.StreamTasksRequest.Init
	6,  // 8: nexus.backend.v1.StreamTasksRequest.call_response:type_name -> nexus.backend.v1.CallResponse
	5,  // 9: nexus.backend.v1.StreamTasksResponse.call_request:type_name -> nexus.backend.v1.CallRequest
	4,  // 10: nexus.backend.v1.CallRequest.MetadataEntry.value:type_name -> nexus.backend.v1.MetadataValues
	4,  // 11: nexus.backend.v1.CallResponse.MetadataEntry.value:type_name -> nexus.backend.v1.MetadataValues
	16, // 12: nexus.backend.v1.CallResponse.Grpc.status_details:type_name -> google.protobuf.Any
	0,  // 13: nexus.backend.v1.BackendService.UpdateServices:input_type -> nexus.backend.v1.UpdateServicesRequest
	2,  // 14: nexus.backend.v1.BackendService.GetServices:input_type -> nexus.backend.v1.GetServicesRequest
	5,  // 15: nexus.backend.v1.BackendService.Call:input_type -> nexus.backend.v1.CallRequest
	7,  // 16: nexus.backend.v1.BackendService.StreamTasks:input_type -> nexus.backend.v1.StreamTasksRequest
	1,  // 17: nexus.backend.v1.BackendService.UpdateServices:output_type -> nexus.backend.v1.UpdateServicesResponse
	3,  // 18: nexus.backend.v1.BackendService.GetServices:output_type -> nexus.backend.v1.GetServicesResponse
	6,  // 19: nexus.backend.v1.BackendService.Call:output_type -> nexus.backend.v1.CallResponse
	8,  // 20: nexus.backend.v1.BackendService.StreamTasks:output_type -> nexus.backend.v1.StreamTasksResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_nexus_backend_v1_service_proto_init() }
func file_nexus_backend_v1_service_proto_init() {
	if File_nexus_backend_v1_service_proto != nil {
		return
	}
	file_nexus_backend_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nexus_backend_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest_Http); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse_Http); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse_Grpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nexus_backend_v1_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTasksRequest_Init); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nexus_backend_v1_service_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CallRequest_Http_)(nil),
	}
	file_nexus_backend_v1_service_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*CallResponse_Http_)(nil),
	}
	file_nexus_backend_v1_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*StreamTasksRequest_Init_)(nil),
		(*StreamTasksRequest_CallResponse)(nil),
	}
	file_nexus_backend_v1_service_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*StreamTasksResponse_CallRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nexus_backend_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_backend_v1_service_proto_goTypes,
		DependencyIndexes: file_nexus_backend_v1_service_proto_depIdxs,
		MessageInfos:      file_nexus_backend_v1_service_proto_msgTypes,
	}.Build()
	File_nexus_backend_v1_service_proto = out.File
	file_nexus_backend_v1_service_proto_rawDesc = nil
	file_nexus_backend_v1_service_proto_goTypes = nil
	file_nexus_backend_v1_service_proto_depIdxs = nil
}
